repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=102400'] # Blocks files larger than 100MB
    -   id: detect-private-key
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, master] # Blocks direct commits to master